# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/ecspresso/main.go
    binary: ecs
    ldflags:
      - -s -w
      - -X main.Version=v{{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
archives:
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  # Visit your project's GitHub Releases page to publish this release.
  # draft: true
